# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lista < Formula
  desc "A simple and aesthetic CLI app to manage your todos on the terminal."
  homepage "https://github.com/kwame-Owusu/lista"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kwame-Owusu/lista/releases/download/v0.7.0/lista_0.7.0_darwin_amd64.tar.gz"
      sha256 "a9907ac3b6ca2474d6fcb36805ea8a4b3e82a8391792ffa69bea054e94b21519"

      define_method(:install) do
        bin.install "lista"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kwame-Owusu/lista/releases/download/v0.7.0/lista_0.7.0_darwin_arm64.tar.gz"
      sha256 "4280dcaf0353e1d9d7181f189de2faee3f77466b678f3ab9e502b19fe163bc3f"

      define_method(:install) do
        bin.install "lista"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kwame-Owusu/lista/releases/download/v0.7.0/lista_0.7.0_linux_amd64.tar.gz"
      sha256 "66e0915cbbbf83e8a90b0408a27399d83be83a84f6b56c57a305806e5f5918c3"
      define_method(:install) do
        bin.install "lista"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kwame-Owusu/lista/releases/download/v0.7.0/lista_0.7.0_linux_arm64.tar.gz"
      sha256 "70f3b70720a7d7f4542a22e511c82aee78d8271eb20b54991a76934ac4bb04c5"
      define_method(:install) do
        bin.install "lista"
      end
    end
  end

  test do
    system "#{bin}/lista", "--version"
  end
end
