# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lista < Formula
  desc "A simple and aesthetic CLI app to manage your todos on the terminal."
  homepage "https://github.com/kwame-Owusu/lista"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kwame-Owusu/lista/releases/download/v0.7.1/lista_0.7.1_darwin_amd64.tar.gz"
      sha256 "a31621635076d07b1960f31756bf1e9846a9a23412b45be18c4beabd229c9b00"

      define_method(:install) do
        bin.install "lista"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kwame-Owusu/lista/releases/download/v0.7.1/lista_0.7.1_darwin_arm64.tar.gz"
      sha256 "884ee55157865ea1a5eeb751a6f6bfc7257a973b5da1e1218ac2b78ed27cd642"

      define_method(:install) do
        bin.install "lista"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kwame-Owusu/lista/releases/download/v0.7.1/lista_0.7.1_linux_amd64.tar.gz"
      sha256 "985c119e8dc6c42c7d92600d623c4af67b8631140ba2aa7a39b04c1a1a71afe7"
      define_method(:install) do
        bin.install "lista"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kwame-Owusu/lista/releases/download/v0.7.1/lista_0.7.1_linux_arm64.tar.gz"
      sha256 "d3bc9cadcb5456dfb43d1922e6581f5fff1051743cd0c2d10f8f234f220d0437"
      define_method(:install) do
        bin.install "lista"
      end
    end
  end

  test do
    system "#{bin}/lista", "--version"
  end
end
